config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :links do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :link
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  validates :title, :url, presence: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  has_many :links
  has_many :comments
  
  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.link_id = params[:link_id]
    @comment.save
    flash[:errors] = @comment.errors.full_messages
    redirect_to link_url(@comment.link)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to link_url(@comment.link)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_login

  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    if @link.save
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = current_user.links.find(params[:id])
    if @link.update_attributes(link_params)
      redirect_to link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  private
  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user
      login(user)
      redirect_to links_url
    else
      flash[:errors] = ['invalid credentials']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to links_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden'
              name='authenticity_token'
              value='#{form_authenticity_token}'".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      Signed in as : <%= current_user.username %>
      <form action="<%=session_url%>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Sign Out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign In</a>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>

    <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<h1>All Links</h1>
<ul>
  <% @links.each do |link| %>
  <li>
    <a href="<%=link_url(link)%>"><%=link.title%></a> : <%=link.url%>
  </li>
  <% end %>
</ul>

  <a href="<%= new_link_url %>">New Link</a>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url %>" method="post">
  <%= auth_token %>
  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>
    Password
    <input type="passsword" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">
</form>